In [1]:
array = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(array)

In [4]:
print(arr)

[1 2 3]


In [5]:
my_list = [2,3,4]

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([2, 3, 4])

In [9]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [10]:
arr2d = np.array(my_mat)

In [11]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [18]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [20]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
np.random.rand(2,3)

array([[ 0.62140264,  0.39970788,  0.81967842],
       [ 0.4779832 ,  0.93490219,  0.06090725]])

In [23]:
arr = np.arange(0,25)

In [24]:
ranarr = np.random.randint(0,50,5)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([24, 25, 28, 34, 18])

In [36]:
ranarr.dtype

dtype('int64')